### ISSUE TITLE
Link error when using CocoaPods

### ISSUE THREAD

**Issue by vbadeasv** [itsthejb/CKCollectionViewDataSourceChangesetBuilder#1]
There is a link error when using CKCollectionViewDataSourceChangesetBuilder with CocoaPods, because CKCollectionViewDataSourceChangesetBuilder.mm is not included in podspec.
The following line, from CKCollectionViewDataSourceChangesetBuilder.podspec,
 s.source_files = s.name + '/**/*.{h,m}'
should be changed to
 s.source_files = s.name + '/**/*.{h,m,mm}'

**Comment by itsthejb** [comment]
Ok! Sorry about that - haven't integrated it into my own project yet so didn't spot it. Will try to do that as soon as I can, or feel free to submit a pr

**Comment by itsthejb** [comment]
Ok https://github.com/itsthejb/CKCollectionViewDataSourceChangesetBuilder/releases/tag/v0.9.1 should fix this
