### ISSUE TITLE
[Question] How to use CKTransactionalComponentDataSourceChangeset

### ISSUE THREAD

**Issue by buithuyen** [itsthejb/CKCollectionViewDataSourceChangesetBuilder#5]
Hi guy,

I will be grateful if you let me know how to use CKTransactionalComponentDataSourceChangeset.
Or could you create a example to use them.

Thanks for advance!

**Comment by itsthejb** [comment]
Hi there,

The best thing to do is have a look at the [test suite](https://github.com/itsthejb/CKCollectionViewDataSourceChangesetBuilder/blob/dev/Tests/CKTransactionalComponentDataSourceChangesetDSLBuilderTests.m). There are examples of all the grammar in there.

**Comment by buithuyen** [comment]
I replace remove item function by CKCollectionViewDataSourceChangesetBuilder but not happened.

``` objective-c
- (void)removeItem:(NSIndexPath*)indexPath {
//    CKArrayControllerInputItems items;
//    items.remove(indexPath);
//    [self enqueueChangesetWithItems:items];

    [CKCollectionViewDataSourceChangesetBuilder build:^(CKCollectionViewDataSourceChangesetBuilder* builder) {
        builder.remove.item(nil).at.indexPath(indexPath);
    }];
}
```

**Comment by itsthejb** [comment]
Hi,

Use the `-build` method to generate a `CKTransactionalComponentDataSourceChangeset`, and then you have to enqueue that to your data source. Something like:

```
CKTransactionalComponentDataSourceChangeset *changeset =
[CKCollectionViewDataSourceChangesetBuilder build:^(CKCollectionViewDataSourceChangesetBuilder* builder) {
        builder.remove.item(nil).at.indexPath(indexPath);
    }].build;
[self.dataSource applyChangeset:changeset mode:CKUpdateModeAsynchronous userInfo:nil];
```

**Comment by buithuyen** [comment]
It work fine for me. Thanks for your help!
